name: Node.js CI

variables:
  - name: project
    value: bus-sanlin-node
  - name: repo
    value: git@github.com:RainKolwa/bus-sanlin-node.git

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/
            if cd ${{ variables.project }}; then git pull; else git clone ${{ variables.repo}} ${{ variables.project }}; fi
            cd ${{ variables.project }}
            git pull origin master
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm i --production
            npm run stop
            npm start
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.KEY }}
