name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy
        env:
          PROJECT_NAME: ${{ github.event.repository.name }}
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/
            if cd ${{ env.PROJECT_NAME }}; then git pull; else git clone git@github.com:${{ github.repository }}.git ${{ env.PROJECT_NAME }}; fi
            cd ${{ env.PROJECT_NAME }};
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
            git pull origin master && npm i --production && npm run stop && npm start
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
