name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PROJECT_NAME: bus-sanlin-node
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/
            if cd ${{ env.PROJECT_NAME }}; then git pull; else git clone git@github.com:$GITHUB_REPOSITORY ${{ env.PROJECT_NAME }}; fi
            cd ${{ env.PROJECT_NAME }}
            git pull origin master
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm i --production
            npm run stop
            npm start
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.KEY }}
